from __future__ import annotations

from datetime import datetime

from fleet_health.models import Anomaly, Escalation, PipelineState


def render_report_markdown(state: PipelineState, report_id: str) -> str:
    """Deterministic markdown assembly; LLM narrative is injected into fleet_summary."""
    lines = [
        f"# Fleet Health & Delivery Report",
        f"",
        f"**Report ID:** `{report_id}`  ",
        f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"",
        f"## Executive Summary",
        f"",
        state.fleet_summary or "_No summary generated._",
        f"",
        f"## Fleet Status",
        f"",
    ]

    critical = sum(1 for a in state.anomalies if a.severity == "critical")
    high = sum(1 for a in state.anomalies if a.severity == "high")
    lines.append(f"- Vessels analysed: **{len(state.snapshots)}**")
    lines.append(f"- Anomalies: **{len(state.anomalies)}** (critical: {critical}, high: {high})")
    lines.append(f"- Shore escalations: **{len(state.escalations)}**")
    lines.append("")

    if state.memory_notes:
        lines.append("## Memory Insights")
        lines.append("")
        for note in state.memory_notes:
            lines.append(f"- {note}")
        lines.append("")

    lines.append("## Vessel Performance")
    lines.append("")
    for vs in state.vessel_summaries:
        lines.append(f"### {vs.get('vessel_name', 'Unknown')} (IMO {vs.get('imo', '')})")
        lines.append("")
        lines.append(vs.get("summary", "_No vessel summary._"))
        lines.append("")

    if state.anomalies:
        lines.append("## Detected Anomalies")
        lines.append("")
        lines.append(_anomaly_table(state.anomalies))

    if state.escalations:
        lines.append("## Shore-Side Escalations")
        lines.append("")
        for esc in state.escalations:
            lines.append(
                f"- **[{esc.severity.upper()}]** {esc.title} — {esc.vessel_name} "
                f"(owner: {esc.owner}, deadline: {esc.deadline})"
            )
            lines.append(f"  - {esc.rationale}")
        lines.append("")

    lines.append("## Tool Trace")
    lines.append("")
    for t in state.tool_trace:
        lines.append(f"- `{t.get('tool')}` → {t.get('result_summary', 'ok')}")
    lines.append("")

    lines.append("---")
    lines.append("_Generated by Fleet Health multi-agent pipeline (LangGraph + Claude)._")
    return "\n".join(lines)


def _anomaly_table(anomalies: list[Anomaly]) -> str:
    rows = ["| Vessel | Type | Severity | Message |", "|--------|------|----------|---------|"]
    for a in anomalies:
        msg = a.message.replace("|", "/")[:80]
        rows.append(f"| {a.vessel_name} | {a.type} | {a.severity} | {msg} |")
    return "\n".join(rows)
